# -*- coding: utf-8 -*-
"""Plagarism_Checker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MrCCGO-SX9UAfMikI3UTc1svHokNODLx
"""

import os

from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.metrics.pairwise import cosine_similarity

files = [doc for doc in os.listdir() if doc.endswith('.txt')]

files

data = [open(_file,encoding='utf-8').read() for _file in files]

data

def vectorizer (t):
  return TfidfVectorizer().fit_transform(t).toarray()

a = vectorizer(data)

a

def similar (x,y):
  return cosine_similarity([x,y])

t = list(zip(files,a))

t

result = set()

def check ():
  global t
  for x,y in t:
    new = t.copy()
    curr = new.index((x,y))
    print(curr)
    del new[curr]
    for p,q in new:
      score = similar(y,q)[0][1]
      ans = sorted((x,p))
      print(similar(y,q))
      print(ans)
      res = (ans[0],ans[1],score)
      result.add(res)
  return result

for i in check():
  print(i)